name: CICD-Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, json, pdo, pdo_mysql, bcmath, fileinfo

    - name: Install Dependencies
      run: |
        cd backend-login
        composer install --no-dev --prefer-dist --optimize-autoloader

    - name: Run Tests
      run: |
        cd backend-login
        php artisan test

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to Staging via SSH
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          ./deploy-training.sh
